from typing import List
from pydantic import BaseModel, Field


class QuestionLabels(BaseModel):
    """Structured question containing the labels."""

    id: str = Field(description="The id used as input.")
    question: str = Field(description="The question text.")
    method: str = Field(description="The method used to generate the labels.")
    labels: List[str] = Field(description="Set of extracted labels.")
    
    def to_question_label(self,):
        """Convert the response to the mapping expected by downstream aggregators."""
        question_label = "The labels generated by '" + self.method + "' are : " + ",".join(self.labels)
        return question_label
